Algoritmo "Graus"
// Lógica de Programação
// Fabricio Curvello 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/05/2024

Var
c, f: real


Inicio
escreval("Informe uma temperatura em graus Fahrenheit")
leia(f)

//c = (f-32) x 5 : 9
c <- (f - 32) * 5 / 9

escreval(f, " graus Fahrenheit = ", e, "graus Celcius")


Fimalgoritmo