Algoritmo "Questão3"
// Lógica de Programação
// Fabricio Curvello 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/05/2024
Var
Peso, altura:real


Inicio
escreval("Indique Seu Peso")
leia(Peso)

escreval("Indique Sua Altura")
leia(altura)

escreval("O Seu Valor De Índice De Massa Corporal É: ", Peso/(altura*altura))


Fimalgoritmo