Algoritmo "Questão 4"
// Lógica de Programação
// Fabricio Curvello 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/05/2024
Var

n:inteiro

Inicio
escreval("Digite um numero inteiro e informarei seu sucessor e antecessor: ")
leia(n)
escreval("O Sucessor de ", n ,"é = ", n + 1)
escreval("O Antecessor de ", n ,"é = ", n - 1)



Fimalgoritmo