Algoritmo "Questão 05"
// Lógica de Programação
// Fabricio Curvello 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/05/2024
Var
// Seção de Declarações das variáveis 
salario, aumento: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Informe seu salário: ")
leia(salario)

aumento <- salario * 0.15

escreval("Seu novo salário: R$", (salario+aumento))

Fimalgoritmo